### ISSUE TITLE
My logo!

### ISSUE THREAD

**Issue by johnrobharrison** [FreesideHull/Branding#3]
Not an issue, but just want to say it's nice to see the logo I made is still being used and great job turning it into an SVG.  It was designed on Adobe Fireworks so the PNG might still be editable in that and exportable to an SVG natively. 

Just for reference, that's the Ubuntu font too.

**Comment by Epictek** [comment]
Awesome! Well let's make this an issue! @sbrl can we give @shinsters credit in the readme as the original author?
Also the font now in use is Open Sans iirc. It looks similar to Ubuntu but I prefer it, it's also more suited to being a web font :)

**Comment by Epictek** [comment]
Also :D
>Adobe Fireworks
![](http://i.imgur.com/V5K7N1I.jpg)

**Comment by sbrl** [comment]
Absolutely, @Epictek!

It's great to see you around here @shinsters! Freeside is very different to what it was then (we have an official student-managed Lab provided by the University now!). What was Freeside like back when you were a student?

I've opened #4. Does that look ok you? If so, I'll merge.

**Comment by fisherthewol** [comment]
It's been a couple of years and we have merged #4; hence I am closing the issue; however feel free to re-open it with discussion!
